// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiwKEAXlS9iC7Sb2eQom1TPaSSqf7EcN4',
    appId: '1:388765248192:web:ac418cf21c9c5439915b25',
    messagingSenderId: '388765248192',
    projectId: 'stimik-1116a',
    authDomain: 'stimik-1116a.firebaseapp.com',
    databaseURL: 'https://stimik-1116a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'stimik-1116a.appspot.com',
    measurementId: 'G-FY4JQLXELW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6sK0jRWUUuPApqQkilWVHzNVrT-6BOBs',
    appId: '1:388765248192:android:d0d3c0c542b2c006915b25',
    messagingSenderId: '388765248192',
    projectId: 'stimik-1116a',
    databaseURL: 'https://stimik-1116a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'stimik-1116a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmO8SqJO_R9cXzF0RLHhZGg5qyYVbIT7o',
    appId: '1:388765248192:ios:808a59ac31e947cc915b25',
    messagingSenderId: '388765248192',
    projectId: 'stimik-1116a',
    databaseURL: 'https://stimik-1116a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'stimik-1116a.appspot.com',
    iosClientId: '388765248192-orr2cjqo6p70hj0pqe9th9ui8njejb4f.apps.googleusercontent.com',
    iosBundleId: 'com.example.newapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmO8SqJO_R9cXzF0RLHhZGg5qyYVbIT7o',
    appId: '1:388765248192:ios:808a59ac31e947cc915b25',
    messagingSenderId: '388765248192',
    projectId: 'stimik-1116a',
    databaseURL: 'https://stimik-1116a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'stimik-1116a.appspot.com',
    iosClientId: '388765248192-orr2cjqo6p70hj0pqe9th9ui8njejb4f.apps.googleusercontent.com',
    iosBundleId: 'com.example.newapps',
  );
}
